 tasks:
   php-sonar-job:
     runner: sonarsource/sonar-scanner-cli
     steps:
     - checkout    
     - commands:
     - |
       sonar-scanner \
         -Dsonar.projectKey=php-app \
         -Dsonar.sources=. \
         -Dsonar.host.url=http://65.2.9.93:9000 \
         -Dsonar.login=afc91185d2865823281b6adcd0ccfd9b8990cc54
